format = """
$os\
[](fg:#d455d6 bg:bright-red)\
$shell\
[](fg:bright-red bg:bright-yellow)\
$battery\
[](fg:bright-yellow bg:yellow)\
$username\
[](fg:yellow bg:blue)\
$directory\
[](fg:blue bg:bright-blue)\
$git_branch\
$git_status\
[](fg:bright-blue bg:bright-cyan)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:bright-cyan bg:cyan)\
$docker_context\
[](fg:cyan bg:green)\
$memory_usage\
[](fg:green bg:bright-green)\
$time\
[](fg:bright-green bg:black)\
$status\
[ ](fg:black)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:yellow"
style_root = "bg:yellow"
format = '[ $user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#d455d6"
format = '[  ]($style)'
disabled = false # Disabled by default

[shell]
disabled = false
style = "bg:bright-red"
format = '[ $indicator ]($style)'

[[battery.display]]
threshold = 40
style = "bg:bright-yellow"

[battery]
charging_symbol = ''
full_symbol = '󰁹'
discharging_symbol = '󰂃'
unknown_symbol = '󰂁'
empty_symbol = '󰂎'
format = '[ $symbol $percentage ]($style)'

[directory]
style = "bg:blue"
format = "[   $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " 󰈙 "
"Downloads" = "  "
"Music" = " 󰝚 "
"Movies" = " 󰨜 "
"Pictures" = "  "
"Public" = "  "
"Desktop" = "  "
"Applications" = "  "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

# Add '$custom' to the format list at the top and follow the same format for adding triangle tabs to show the number of directories and files. Then uncomment the two sections below.
# [custom.directories]
# description = "Show directory count count for current directory"
# command = "find ./ -maxdepth 1 -type d | tail -n +2 | wc -l"
# style = "bg:bright-green"
# format = "[  $output]($style)"
# when = "true"
# 
# [custom.files]
# description = "Show files count for current directory"
# command = "find ./ -maxdepth 1 -type f | wc -l"
# style = "bg:bright-green"
# format = "[󰈢 $output ]($style)"
# when = "true"

[c]
symbol = " "
style = "bg:bright-cyan"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:green"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = ""
style = "bg:bright-cyan"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:bright-cyan"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:bright-blue"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:black bg:bright-blue"
format = '[$all_status$ahead_behind$up_to_date ]($style)'
up_to_date = '✓'

[golang]
symbol = ""
style = "bg:bright-cyan"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:bright-cyan"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ""
style = "bg:bright-cyan"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:bright-cyan"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ""
style = "bg:bright-cyan"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:bright-cyan"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥"
style = "bg:bright-cyan"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:bright-cyan"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = ""
style = "bg:bright-cyan"
format = '[ $symbol ($version) ]($style)'

[memory_usage]
disabled = false
threshold = 65
symbol = '󰍛'
style = "bg:green"
format = '[ $symbol $ram_pct ]($style)'

[time]
disabled = false
time_format = "%I:%M" #Hour:Minute Format
style = "bg:bright-green"
format = '[ $time ]($style)'

[status]
style = "bg:black"
symbol = ''
success_symbol = ''
not_executable_symbol = ''
not_found_symbol = '󰦀'
sigint_symbol = '󰚌'
format = '[ $symbol ]($style)'
map_symbol = true
disabled = false 
